In [1]:
!pip install numpy --upgrade 

Requirement already up-to-date: numpy in /home/aouatef/miniconda3/lib/python3.7/site-packages (1.16.2)
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import numpy as np


In [3]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [4]:
numbers=[9,8,7,6]
array_two = np.array(numbers)
array_two



array([9, 8, 7, 6])

In [5]:
array_of_zeroes=np.zeros((3,4))
array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
array_of_ones=np.ones((3,4),dtype=np.int16)
array_of_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [7]:
empty_array=np.empty((2,3))
empty_array


array([[4.66647654e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [8]:
array_eye=np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
array_of_evens=np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
array_of_floats=np.arange(0,2,0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [11]:
array_2d=np.array([(1,2,3),(4,5,6)])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array_2d.shape

(2, 3)

In [13]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [14]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
array_ones=np.ones_like(array_2d)
array_ones

array([[1, 1, 1],
       [1, 1, 1]])